<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pick a languageJavaScriptPythonJavaCRuby</name>
   <tag></tag>
   <elementGuidId>a10d95ab-6224-44f4-b49c-f4b29f760ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#options</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='options']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#options</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>58b3becb-61e8-490e-ab9b-e608f0cad3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>512837de-11ce-478d-bd20-0a9fdb9ce565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields[programming_language]</value>
      <webElementGuid>de23b8e1-060b-47c1-a5a7-53932a925c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick a languageJavaScriptPythonJavaC#Ruby</value>
      <webElementGuid>2bc684a7-2e36-425b-b3f0-034b816ab3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;options&quot;)</value>
      <webElementGuid>57681bbd-ea20-4bbd-9a14-b3fc65212655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='options']</value>
      <webElementGuid>e0df979c-d5de-4353-9f73-22bd10aece62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/main/div/div/div/div/div/form/select</value>
      <webElementGuid>47b033c7-dbf6-4734-a73e-44988f38ce7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One email every Tuesday. Unsubscribe anytime.'])[1]/following::select[1]</value>
      <webElementGuid>bad46922-a776-4316-a617-e6bd045dd76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/following::select[1]</value>
      <webElementGuid>9dc10719-d45c-4941-9889-7f341ab2279b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip it, take me to the tips! →'])[1]/preceding::select[1]</value>
      <webElementGuid>c25cbab5-d2f1-434f-b7df-026c972a6812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tips by Level:'])[1]/preceding::select[1]</value>
      <webElementGuid>726af965-507a-4242-a453-7c40c52ee5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d5ee3a95-34f3-4f16-84e7-bc68d16980d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'options' and @name = 'fields[programming_language]' and (text() = 'Pick a languageJavaScriptPythonJavaC#Ruby' or . = 'Pick a languageJavaScriptPythonJavaC#Ruby')]</value>
      <webElementGuid>0110ee2f-0e0d-40c1-b5b8-ab1055faeaed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
