<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mentorship</name>
   <tag></tag>
   <elementGuidId>09f8e607-4df2-45be-a3b7-51834f7e9ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Mentorship')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mentorship&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e6f8e0f-3a1a-4b26-8f02-4d9e1efb2603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mentorship</value>
      <webElementGuid>9d632ca9-5591-4b3e-9799-fa29d521bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mentorship</value>
      <webElementGuid>368d6365-971a-4772-9637-6703bb744789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;main-header&quot;]/div[@class=&quot;header-upper&quot;]/div[@class=&quot;auto-container&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;nav-outer clearfix&quot;]/nav[@class=&quot;main-menu&quot;]/div[@class=&quot;navbar-collapse collapse clearfix&quot;]/ul[@class=&quot;navigation clearfix&quot;]/li[5]/a[1]</value>
      <webElementGuid>6291893e-2d79-4308-9383-c925b890b981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Orange_HRM/Page_Practice Page/iframe_iFrame Example_iframe-name</value>
      <webElementGuid>23f1e50c-84d3-4cc3-be4f-ac67785ff088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mentorship')]</value>
      <webElementGuid>e1b4c941-7d25-443c-91a1-b66755ad7b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning paths'])[1]/following::a[1]</value>
      <webElementGuid>e242def6-b1b9-416f-89cc-902c2d256bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Access plan'])[1]/following::a[2]</value>
      <webElementGuid>3d992686-efd1-4db4-a581-fc4645ff5569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Support'])[1]/preceding::a[1]</value>
      <webElementGuid>c3e302d2-2959-452d-8d95-db268f08d760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice'])[1]/preceding::a[2]</value>
      <webElementGuid>e5d1f5c5-7d94-4d82-8cd5-7f39fe8075e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mentorship']/parent::*</value>
      <webElementGuid>fccd1966-b4c6-457b-a4e1-c28f874317d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mentorship')]</value>
      <webElementGuid>ce46b0df-13ff-4da9-866a-4c202d25e97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>3a86c3ba-bad0-48c2-908a-e831453a3f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mentorship' and (text() = 'Mentorship' or . = 'Mentorship')]</value>
      <webElementGuid>8150df8e-4f10-4bc7-9b4c-5ad09718ac95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
