<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open Tab</name>
   <tag></tag>
   <elementGuidId>0fe6bcf9-4955-4468-98c2-cc025a91e346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opentab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='opentab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Open Tab&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>165f304e-bf32-48aa-9c74-2487e1d4fad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opentab</value>
      <webElementGuid>a21160cc-7b8c-4e0f-966f-0fc355c92eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class1 class2</value>
      <webElementGuid>af7fe1fe-da38-49fa-b782-5a21e813b005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.qaclickacademy.com</value>
      <webElementGuid>ef8e6423-9b6d-4f84-b8cf-5d756e7601df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0c01fb9e-ec66-4704-a8c4-36c83d385576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Tab</value>
      <webElementGuid>6a83143b-8ecd-42e8-9b77-0b037281e9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opentab&quot;)</value>
      <webElementGuid>98f229fa-f319-4a66-8928-c0bd216acd65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='opentab']</value>
      <webElementGuid>15ec23ec-a743-4bde-8546-738f4b41196a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open Tab')]</value>
      <webElementGuid>0240927f-622d-4b83-98e8-7a40a6b408a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch Tab Example'])[1]/following::a[1]</value>
      <webElementGuid>7b9b3034-4ce1-4d82-94bc-bb4e958dcf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Window'])[1]/following::a[1]</value>
      <webElementGuid>f2fc164c-6bed-4a51-a8b0-12eb698a282d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch To Alert Example'])[1]/preceding::a[1]</value>
      <webElementGuid>7d28af7f-ff5d-4b03-95f6-45ebb6532927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Table Example'])[1]/preceding::a[1]</value>
      <webElementGuid>c972f1b4-10e6-4091-baee-c9ea57f14316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open Tab']/parent::*</value>
      <webElementGuid>a4acdf46-9d3b-49a9-8bff-e34db476f518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.qaclickacademy.com')]</value>
      <webElementGuid>a3ee26e7-bcac-4d45-bac7-00c6e91c47e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/a</value>
      <webElementGuid>b516ec75-c205-4dfa-b7f6-301b60fb2eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'opentab' and @href = 'https://www.qaclickacademy.com' and (text() = 'Open Tab' or . = 'Open Tab')]</value>
      <webElementGuid>984fe8ef-4ca1-4fb2-b440-16400e38019f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
