<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Open Window</name>
   <tag></tag>
   <elementGuidId>abc5ca4f-e0b4-4c57-9a10-6993c0939dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#openwindow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='openwindow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Open Window&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9372373a-5e1b-4876-8a25-afab03cd1ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>openwindow</value>
      <webElementGuid>53b8301d-e0a5-4bfe-b200-97dcb28ff428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class1</value>
      <webElementGuid>d5962c4c-f2c7-460e-b4d6-fda6f6e0f679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openWindow()</value>
      <webElementGuid>60b8f41f-00d5-4896-a3fb-63402929d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Window</value>
      <webElementGuid>33e05f43-6609-4e6b-a095-47c372466cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;openwindow&quot;)</value>
      <webElementGuid>f697c092-4c71-4332-9c98-b51d6db66f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='openwindow']</value>
      <webElementGuid>906db211-3313-470a-8875-363bc582d4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch Window Example'])[1]/following::button[1]</value>
      <webElementGuid>e689c368-3dbd-40cb-9d4f-b804104dbcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch Tab Example'])[1]/preceding::button[1]</value>
      <webElementGuid>3ad33fd6-98f1-4696-af35-49bc5d372c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Tab'])[1]/preceding::button[1]</value>
      <webElementGuid>be553673-85c5-4a60-a41e-1d93123740e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open Window']/parent::*</value>
      <webElementGuid>9a86f501-5856-4414-b25c-3ae3c0a42e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/button</value>
      <webElementGuid>4c5dd6a5-f978-4519-ae62-42e85b24fc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'openwindow' and (text() = 'Open Window' or . = 'Open Window')]</value>
      <webElementGuid>ffb63e27-1a43-493f-ae38-279836c3b5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
