<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_British Indian Ocean Territory</name>
   <tag></tag>
   <elementGuidId>03907a04-ce07-4cb8-8e2f-22a3a8f0dc48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-38</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-38']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui-id-38</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ca957c5-9c44-4983-b09b-1aa3a2ed585f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-38</value>
      <webElementGuid>ff1631bc-7650-45ea-afc4-bb74b68bd517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1af3fcbd-f86b-44a8-bb4d-c9540f8d71f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>36d1dd79-ce68-4e20-bc2a-9ddd95bd5ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>British Indian Ocean Territory</value>
      <webElementGuid>aaaddc05-81ec-414d-910a-07364b63ee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-38&quot;)</value>
      <webElementGuid>393e3b0e-feba-4c36-bbf8-75d1cfc6dfc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-38']</value>
      <webElementGuid>02e30493-38d9-46f3-b3ec-5a34056589a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li/div</value>
      <webElementGuid>9100dcde-a7f7-4895-b235-d856ec7a569c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medianh Consulting'])[1]/following::div[1]</value>
      <webElementGuid>c9b17b2b-57bc-4a39-bf2c-48edeac9a01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::div[1]</value>
      <webElementGuid>a38e28ba-eaa5-414f-ab73-910cf0db6f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='British Indian Ocean Territory'])[2]/preceding::div[4]</value>
      <webElementGuid>c580a37a-cfbc-4ff5-a1b6-a005c02980f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='British Indian Ocean Territory']/parent::*</value>
      <webElementGuid>e9d67e18-79a8-404c-9164-85cc05c2537c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>5f078381-f9b2-47c9-9543-a9f8f4df7b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-38' and (text() = 'British Indian Ocean Territory' or . = 'British Indian Ocean Territory')]</value>
      <webElementGuid>f7522374-8e92-4072-baca-6e53be21f903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
