<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Element Displayed Example_show-textbox</name>
   <tag></tag>
   <elementGuidId>28c16b2c-d3aa-455c-bf94-124305f5de0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f9a6188-a69e-4d19-aef8-3a2397849f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-textbox</value>
      <webElementGuid>7c6de47d-45dd-437f-bdaa-390287b1d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>b349ebb0-4761-48eb-8531-c8ebc73de92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>182a715d-524e-4dd3-842e-de22fc7f16a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showElement()</value>
      <webElementGuid>82bfc140-07ea-463f-b9c9-7922c60da496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ecf2ca5e-a254-43f1-a4b7-d39f2c713010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-textbox&quot;)</value>
      <webElementGuid>9ef0b624-4093-4833-bddd-74f0681cfefb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-textbox']</value>
      <webElementGuid>b7175d3b-d3ac-439b-ac26-c26275958af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[2]</value>
      <webElementGuid>021d586c-3c92-45d6-984e-b9c2e270cece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'show-textbox' and @type = 'submit']</value>
      <webElementGuid>ff9b8660-4252-4d1f-810c-9e7ca3e4251a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
