<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option3_checkBoxOption3</name>
   <tag></tag>
   <elementGuidId>317568f8-0d1e-48f7-8a50-1b317cc0d090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxOption3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxOption3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBoxOption3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>229c891f-ec05-4d0f-b177-17e1e05366f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxOption3</value>
      <webElementGuid>ee3ed73d-5105-4d85-9a3d-fa9a55b955c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option3</value>
      <webElementGuid>67f2bb57-cd93-44ae-9b62-b0096cce79d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxOption3</value>
      <webElementGuid>dd62a1f9-37e7-4df2-ae61-83626797feae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>75adc32c-91e9-45c2-84bf-610735c0dbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxOption3&quot;)</value>
      <webElementGuid>e3efffa4-462b-4a99-b3e0-822062fbfd08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxOption3']</value>
      <webElementGuid>d573ca51-a068-4ebc-92ff-1dc7a25e3900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-example']/fieldset/label[3]/input</value>
      <webElementGuid>98b0099c-bba1-4f3f-a453-2d74d8c887dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label[3]/input</value>
      <webElementGuid>253470d1-3b89-4831-86de-073154dfbe43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkBoxOption3' and @name = 'checkBoxOption3' and @type = 'checkbox']</value>
      <webElementGuid>e83bd49f-44d1-4176-bbd2-033158b409ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
