<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Element Displayed Example_hide-textbox</name>
   <tag></tag>
   <elementGuidId>9d65b4c2-cb1b-450a-abf4-7486d89218dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide-textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hide-textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Hide&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77752f71-6af0-41d6-9248-47e0d0823009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide-textbox</value>
      <webElementGuid>1b8aefb0-e8da-48b1-aad2-1ec5727fdc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>83f8540d-98b7-4f19-9644-e1fc12d69f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>b494402f-6f46-48d9-ba1e-5970cbd6f37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideElement()</value>
      <webElementGuid>2fd34785-5e57-4795-bc53-2ff4a68c3107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7b0166c8-0f96-497b-a1e9-a028c753429e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide-textbox&quot;)</value>
      <webElementGuid>d45ff4c0-61a4-4266-88cb-c889251b4620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hide-textbox']</value>
      <webElementGuid>de5dd7c0-3f4f-4a8f-adb2-ab5f86cf302c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/fieldset/input</value>
      <webElementGuid>d5ecd305-671c-4aee-9586-f61836967a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hide-textbox' and @type = 'submit']</value>
      <webElementGuid>0b21bef6-2f30-4b2a-a733-87cff3f270ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
