<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Element Displayed Example_show-hide</name>
   <tag></tag>
   <elementGuidId>6ce186c6-92d5-43bd-816b-d4b5ecec3996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayed-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayed-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Hide/Show Example&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>169581c2-1ff7-45d5-8abd-eff16d0f4d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayed-text</value>
      <webElementGuid>6e3ee5e6-43df-43eb-b043-ca942b7383e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-hide</value>
      <webElementGuid>52a43266-f14d-4a54-90d6-743ebb2593d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputs displayed-class</value>
      <webElementGuid>0ffff1fd-2602-4102-a3ac-38c6616712f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hide/Show Example</value>
      <webElementGuid>b8758c12-acfb-4277-8ad7-07a8b9175965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92d65236-2220-4721-ab25-7806fea7810b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayed-text&quot;)</value>
      <webElementGuid>0c9ed91c-bd3f-4922-8f9d-9ef65b7161d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayed-text']</value>
      <webElementGuid>57cf3963-9d2f-4d0e-bf0e-aa47938f189b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[3]</value>
      <webElementGuid>10f15890-23cd-4ea3-ab12-2789aa73c80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayed-text' and @name = 'show-hide' and @placeholder = 'Hide/Show Example' and @type = 'text']</value>
      <webElementGuid>56f50915-4b4b-4c91-9f16-d0e23c4f7ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
