<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option2_checkBoxOption2</name>
   <tag></tag>
   <elementGuidId>5adf7c02-3d05-4af9-8109-9028a6991716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxOption2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxOption2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBoxOption2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6033009-b1be-4b9d-80b0-c7ab0b17a15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxOption2</value>
      <webElementGuid>bbefd8f8-9091-4c96-bcc3-86f4756410be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option2</value>
      <webElementGuid>ea155045-6fce-4d7f-823d-c80a4794fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxOption2</value>
      <webElementGuid>61c87ef5-bf7c-421a-9638-4f95ed23d2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85a34ec6-baee-4438-9242-01bffd687c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxOption2&quot;)</value>
      <webElementGuid>a6d885b5-b57b-4ea6-85ba-f3ff92b7b878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxOption2']</value>
      <webElementGuid>8cff2ec5-7a54-4b0e-a20d-2b048a29dda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-example']/fieldset/label[2]/input</value>
      <webElementGuid>823fb027-046f-4b57-855b-7cc710191e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label[2]/input</value>
      <webElementGuid>e97feeec-33df-43cd-89ab-4eb9ceaf3566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkBoxOption2' and @name = 'checkBoxOption2' and @type = 'checkbox']</value>
      <webElementGuid>1f7b95aa-8c54-4fef-9dd1-3b87534f7518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
