<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option1_checkBoxOption1</name>
   <tag></tag>
   <elementGuidId>316793f2-428a-4d98-9331-b9c43fe8a9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxOption1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxOption1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBoxOption1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b580bc55-1307-492a-a17b-acb49f731b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxOption1</value>
      <webElementGuid>94ff543a-111f-4f1f-8ffc-0122a9bef226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option1</value>
      <webElementGuid>cfcefbba-2af2-4d94-9dfc-c6c88c07bdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxOption1</value>
      <webElementGuid>c769e09d-c466-482e-84f5-4788ae37144b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b8da8cb-a97d-4c39-a420-160228cbd38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxOption1&quot;)</value>
      <webElementGuid>ea5d7dbf-250c-4263-941d-3a8d2c04eec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxOption1']</value>
      <webElementGuid>6440518b-278d-46e0-a6a3-0a8ec9a3faac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-example']/fieldset/label/input</value>
      <webElementGuid>c4c4fc27-7a9d-41cc-93f1-52992569d524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label/input</value>
      <webElementGuid>8133d16d-732d-4750-947f-b8e6444d6e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkBoxOption1' and @name = 'checkBoxOption1' and @type = 'checkbox']</value>
      <webElementGuid>f55178b9-e682-4e0c-8f22-c2c41bea24bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
