<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     Option1  _bf898a</name>
   <tag></tag>
   <elementGuidId>cc336854-ca98-4d1c-9775-0d52d58af3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdown-class-example</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown-class-example']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dropdown-class-example</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07c9d5a2-d640-4a78-8716-dadc52e0e769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>09ce02d7-16f9-4753-807b-0f1ed51fe4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>061f4623-9fee-4da7-8c32-ff6488210b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Select
                     Option1
                    Option2
                    Option3
                </value>
      <webElementGuid>4004035f-774a-4f27-a8b1-6361f58f4888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-class-example&quot;)</value>
      <webElementGuid>5c512987-6dae-482a-9cd2-a6614a119bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown-class-example']</value>
      <webElementGuid>d3f08fd6-395d-426f-a237-154f1b36ce4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/following::select[1]</value>
      <webElementGuid>1cc11331-0c68-4daa-be31-0d3ea4028cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggession Class Example'])[1]/following::select[1]</value>
      <webElementGuid>6f84291a-e3e6-444a-8907-83be0bccd16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::select[1]</value>
      <webElementGuid>aec82368-65f7-4a05-83e3-4f9bd360a9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a578a71d-2b85-401e-b59e-7fc27a1c898e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown-class-example' and @name = 'dropdown-class-example' and (text() = '
                     Select
                     Option1
                    Option2
                    Option3
                ' or . = '
                     Select
                     Option1
                    Option2
                    Option3
                ')]</value>
      <webElementGuid>3f3b50c4-3f56-4182-967f-bd60d0476107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
