<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Elemental Selenium</name>
   <tag></tag>
   <elementGuidId>b322048c-3e4c-4e6a-aa52-e35286a18c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.large-4.large-centered.columns > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-footer']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Elemental Selenium&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac436033-e2cf-4ed7-8404-ad9c508a6b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2dd0d914-0762-4aed-bfcf-5f183ce6eca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://elementalselenium.com/</value>
      <webElementGuid>7c702f2e-88c9-4be7-a002-1bf9bd30a432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elemental Selenium</value>
      <webElementGuid>a1b9e60f-c1c5-4afd-90eb-f3f2b74f7907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-footer&quot;)/div[@class=&quot;large-4 large-centered columns&quot;]/div[1]/a[1]</value>
      <webElementGuid>b0b2cef3-8fdf-442d-95e0-35f67e11071f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-footer']/div/div/a</value>
      <webElementGuid>30ffcdd2-ee67-4df9-a191-357f78970f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Elemental Selenium')]</value>
      <webElementGuid>f207fa4b-8bae-40de-a422-75bbc08a9475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken Images'])[1]/following::a[1]</value>
      <webElementGuid>27bb8f19-3bec-4447-9ee9-e30b2aecd75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Elemental Selenium']/parent::*</value>
      <webElementGuid>96e5721b-de8b-4d45-ad02-8be231cd1ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://elementalselenium.com/']</value>
      <webElementGuid>6bb5f914-c994-4361-b37b-cf37d8f44857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>c2e7d1e0-74df-49ab-b269-ed86d14f592c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://elementalselenium.com/' and (text() = 'Elemental Selenium' or . = 'Elemental Selenium')]</value>
      <webElementGuid>a41f0269-0689-4da1-8773-de14b11fc837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
