<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Example 1 Element on page that is hidden</name>
   <tag></tag>
   <elementGuidId>c639b683-3f54-45b6-87b1-c43680667c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.example > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Example 1: Element on page that is hidden&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5cc4f9a-7385-45b6-9ba1-52f551e8d8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dynamic_loading/1</value>
      <webElementGuid>574213eb-566f-418b-912f-4635e4c0cb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Example 1: Element on page that is hidden</value>
      <webElementGuid>c852c94f-0694-41bf-b2ee-74c13839e647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[1]</value>
      <webElementGuid>8dbd9075-7aa7-4d86-8915-a620d805bd61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a</value>
      <webElementGuid>28c33061-e29f-4fc8-a655-c823bdefbdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Example 1: Element on page that is hidden')]</value>
      <webElementGuid>9376b709-a62c-4c0b-8354-636bbe73d2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamically Loaded Page Elements'])[1]/following::a[1]</value>
      <webElementGuid>29b17d6d-125c-4500-b474-1c190a159a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example 2: Element rendered after the fact'])[1]/preceding::a[1]</value>
      <webElementGuid>0ea650ed-d32f-41c9-8746-9274204fb61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Example 1: Element on page that is hidden']/parent::*</value>
      <webElementGuid>098a5fb9-b400-466b-a977-cfc74fcf72c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dynamic_loading/1')]</value>
      <webElementGuid>937a0420-c728-47d1-8dc1-c5ce043b2c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>7545b331-6ac0-4a7b-8e9c-2fcc992ccbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dynamic_loading/1' and (text() = 'Example 1: Element on page that is hidden' or . = 'Example 1: Element on page that is hidden')]</value>
      <webElementGuid>3109fd05-66ef-4fc4-9210-5b2f08d8e038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
