<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_foo</name>
   <tag></tag>
   <elementGuidId>688f5fed-221e-4653-af55-bb5a66fc7576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d1c2eb70-5e0f-013d-d3a2-761a768c7220</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='d1c2eb70-5e0f-013d-d3a2-761a768c7220']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;foo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a234a5df-a24c-49be-b353-5afab10e0826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d1c2eb70-5e0f-013d-d3a2-761a768c7220</value>
      <webElementGuid>9954e96c-c29a-45fc-a158-669ed2fba83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4a79324-3b1a-4a89-ab42-2bca4f3b15f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>foo</value>
      <webElementGuid>9238be19-a885-48a0-92e1-ab3eba59845e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d1c2eb70-5e0f-013d-d3a2-761a768c7220&quot;)</value>
      <webElementGuid>f4e825c5-815f-4fa3-b5bf-7603b8202b9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='d1c2eb70-5e0f-013d-d3a2-761a768c7220']</value>
      <webElementGuid>7b7d6b88-f7a9-4378-8401-17de39df554f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a</value>
      <webElementGuid>28ec6373-0dc9-4496-a7b2-14f134191cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'foo')]</value>
      <webElementGuid>b8dc3196-291f-4441-9568-38f693f11890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[1]</value>
      <webElementGuid>0c99e1c4-38a6-41b4-9f99-c681b0017f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/preceding::a[1]</value>
      <webElementGuid>78d35826-1f8e-4a05-8872-86e3170073a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[1]/preceding::a[2]</value>
      <webElementGuid>c49d3f24-c4ff-4f28-9b1e-08dc2231fd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='foo']/parent::*</value>
      <webElementGuid>17ab58b0-a072-4fb3-ba1d-7e01989aaf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[2]</value>
      <webElementGuid>50b5f035-3a90-428d-a88a-41374b835c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>9278eda7-a126-4a1f-a564-e499d0c67276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'd1c2eb70-5e0f-013d-d3a2-761a768c7220' and (text() = 'foo' or . = 'foo')]</value>
      <webElementGuid>4f590e7b-9c2d-4758-9c21-003be0ae3c3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
