<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_karate-logo.png</name>
   <tag></tag>
   <elementGuidId>68d61d69-7fc9-4c09-a602-afa65f75571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(9)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;karate-logo.png&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ab5ed7c-a9af-4749-8ee6-c5232dceb0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/karate-logo.png</value>
      <webElementGuid>75b07166-de51-47a8-b010-d8006795bc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>karate-logo.png</value>
      <webElementGuid>dcb7941b-e906-4c7e-9bff-8acff9c6a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[9]</value>
      <webElementGuid>0f175068-e2f1-4a28-951f-8a80dd1135c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a[9]</value>
      <webElementGuid>2fdf7507-2721-4352-a700-9975521b0b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'karate-logo.png')]</value>
      <webElementGuid>a08b694c-21a0-4de4-863c-9213cc849215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cypress.png'])[1]/following::a[1]</value>
      <webElementGuid>425decab-2df1-4233-a521-17c8a2837e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ce28d30ttx_Screenshot (2).png'])[1]/following::a[2]</value>
      <webElementGuid>d6a23f8a-669f-449d-bf7d-168f5a2d5089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jpeg_with_exif.jpeg'])[1]/preceding::a[1]</value>
      <webElementGuid>b888823d-75a1-4364-bb0f-dd3284340215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test.txt'])[1]/preceding::a[3]</value>
      <webElementGuid>5e39850c-9b51-48f9-b509-1b6ef3e6d008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='karate-logo.png']/parent::*</value>
      <webElementGuid>9e7d7608-4f87-4add-a3e3-eb795b92c629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/karate-logo.png')]</value>
      <webElementGuid>23566389-60d1-46da-89b2-b1962f22a4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]</value>
      <webElementGuid>2f1fded5-7736-47ba-bb23-374b4a773f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/karate-logo.png' and (text() = 'karate-logo.png' or . = 'karate-logo.png')]</value>
      <webElementGuid>34f38687-bbf5-4be8-a4c6-116660bebb2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
