<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Context Menu_hot-spot</name>
   <tag></tag>
   <elementGuidId>9c836f57-299a-4192-aece-ee9908016db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hot-spot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hot-spot']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hot-spot</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55263850-f9b6-40f2-b369-8b3bf20cb95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hot-spot</value>
      <webElementGuid>51c5a62e-3796-45d9-93c0-945e206f5569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncontextmenu</name>
      <type>Main</type>
      <value>displayMessage()</value>
      <webElementGuid>ce2cd38b-8e57-44cc-a913-cac2a3f55036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hot-spot&quot;)</value>
      <webElementGuid>6d81cbdd-d70e-4295-ae89-4fccab6123b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hot-spot']</value>
      <webElementGuid>5716e42a-ddb9-494f-a883-4d7ac45ab936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>acde5dcd-8164-44c7-a31b-426cd3415b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Context Menu'])[1]/following::div[1]</value>
      <webElementGuid>2cc7d321-e8d4-4181-933c-c446d4ebc6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::div[1]</value>
      <webElementGuid>3931e871-f881-4745-b6f5-13e8123ccb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>a609fc03-6bfb-4dbd-a3e7-809cfe6a3735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hot-spot']</value>
      <webElementGuid>5e1369ed-71ec-4b95-87a6-fecfa8248cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
