<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contact</name>
   <tag></tag>
   <elementGuidId>07769f48-817b-4d35-81f4-f09bc927fe5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.contact > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPanel']/ul[2]/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;contact&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d36fcbf-26e2-4437-af28-4fac95f77cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>contact.htm</value>
      <webElementGuid>a3bf8c37-44b4-48b9-97b8-7e4d244564a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>798c91dd-39b0-47f6-aa66-4c2e2c359e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPanel&quot;)/ul[@class=&quot;button&quot;]/li[@class=&quot;contact&quot;]/a[1]</value>
      <webElementGuid>de72443f-7017-409c-b8b8-c5b44847459a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPanel']/ul[2]/li[3]/a</value>
      <webElementGuid>67210682-8168-4079-b77b-878818e4dc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'contact')]</value>
      <webElementGuid>bf2e045d-0bd8-4701-b806-b8ad16297160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about'])[1]/following::a[1]</value>
      <webElementGuid>11852cd7-f598-4247-ba0a-d0126c3eae82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='home'])[1]/following::a[2]</value>
      <webElementGuid>6e04ffa7-77c2-424f-8af9-43427eeda17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/preceding::a[1]</value>
      <webElementGuid>76bc0952-a381-4693-8884-241bac10c143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Services'])[1]/preceding::a[1]</value>
      <webElementGuid>e5c48bb4-4f60-4a27-9c44-46f647ec1dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='contact']/parent::*</value>
      <webElementGuid>cd121dae-f257-4fd8-abca-dbac7fae05e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'contact.htm')]</value>
      <webElementGuid>06bab80c-8d86-441f-ba4d-3211ffd7a494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>147708c2-c77d-4baf-bc4b-7df68ae958a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'contact.htm' and (text() = 'contact' or . = 'contact')]</value>
      <webElementGuid>dd020f31-bb70-4764-9702-45a2c419d390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
