<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Down Payment_downPayment</name>
   <tag></tag>
   <elementGuidId>a559db54-acf7-4b7f-a1ed-f06bf0c96644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#downPayment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec7b0c7-5ff9-4b86-8bc4-b48d084fa457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downPayment</value>
      <webElementGuid>8f8a9808-07d1-4b10-8666-86728d109302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bb67ca1-dcf8-4407-aa75-0bc524d1c55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downPayment&quot;)</value>
      <webElementGuid>2c40f0b2-21cb-4e3a-baa4-9bd6b0b7a579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downPayment']</value>
      <webElementGuid>d7fde13e-fca7-41e1-a146-0d6d8b4996a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requestLoanForm']/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>2b6e606e-fe78-4491-a9a9-5b4ad7389e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>74aa8b31-e3ef-4c2f-becd-6d54d95e3b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'downPayment']</value>
      <webElementGuid>fb6713fc-376b-47fa-8976-810096846747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
