<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visible After 5 Seconds</name>
   <tag></tag>
   <elementGuidId>4a1112f0-1a84-4664-a382-776c0836c72d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visibleAfter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='visibleAfter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Visible After 5 Seconds&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>180d6600-7a2e-40e8-8382-8c4350429e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visibleAfter</value>
      <webElementGuid>b4914215-8be9-4674-9b34-348cb035a4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17872eb7-66dd-4363-a0e1-230e9f5b89ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 btn btn-primary</value>
      <webElementGuid>f22c6556-4fab-4408-a983-4965efcc27e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visible After 5 Seconds</value>
      <webElementGuid>d7ff4b65-05f9-4987-8b9f-be931cf24dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibleAfter&quot;)</value>
      <webElementGuid>d3dbf1c4-5077-4c93-b6a4-fd00dd08a646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='visibleAfter']</value>
      <webElementGuid>fe96c781-62bd-470a-a19e-c7d55da2bd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/button[3]</value>
      <webElementGuid>e56fb52a-db0e-474d-9bd4-1c668aa203e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color Change'])[1]/following::button[1]</value>
      <webElementGuid>5c4ae976-ec0a-47d5-b8a4-474848874068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will enable 5 seconds'])[1]/following::button[2]</value>
      <webElementGuid>842be2ce-e5e8-4904-a529-8e1e2c95c4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::button[1]</value>
      <webElementGuid>15ecbf46-083a-437f-a270-34cfd99e4185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visible After 5 Seconds']/parent::*</value>
      <webElementGuid>e748f413-36c8-49c5-a7b0-eb4674590118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>150ffcbe-2812-4ead-a966-b3bdfe8ecf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'visibleAfter' and @type = 'button' and (text() = 'Visible After 5 Seconds' or . = 'Visible After 5 Seconds')]</value>
      <webElementGuid>c70af205-0f54-4ff6-9678-2a3b66a9c73b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
